version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      MONGO_URI: 
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: : /mongo-seed
    links: 
      - mongo